- name: Configure SQL Server using lowlydba.sqlserver collection
  hosts: win
  gather_facts: no
  vars:
    instance_name: "WIN-8FEC7TK3JN0\\SQLEXPRESS"
  tasks:
      - name: Get basic info for an instance
  lowlydba.sqlserver.instance_info:
    sql_instance: "{{ instance_name }}"

