---
- name: Get basic info for an instance
  hosts: win
  gather_facts: no
  vars:
    sql_instance: "WIN-8FEC7TK3JN0\\SQLEXPRESS"

  tasks:
    - name: Get instance info
      lowlydba.sqlserver.instance_info:
        sql_instance: "{{ sql_instance }}"

