- name: Configure SQL Server using lowlydba.sqlserver collection
  hosts: win
  gather_facts: no
  vars:
    instance_name: "WIN-8FEC7TK3JN0\\SQLEXPRESS"
  tasks:
    - name: Ensure NT AUTHORITY SYSTEM account is not used for administration
      lowlydba.sqlserver.login:
        instance_name: "{{ instance_name }}"
        login: "NT AUTHORITY\\SYSTEM"
        sysadmin: no
        state: present
      become: runas

