---
- name: Combined SQL Server Configuration
  hosts: all
  gather_facts: true
  become: yes
  become_method: runas
  become_user: WinLabAAP #is admin

  vars:
    permission: "VIEW ANY DATABASE"  # Real Permissions
    sql_instance_id: "MSSQLSERVER" # Specify the SQL Server instance name here

  tasks:
    - name: Install pymssql Python module
      win_shell: |
        Install-Module -Name pymssql -Force -Scope Global
      become: yes
      become_user: WinLabAAP
      environment:
        PYTHONIOENCODING: UTF-8

    - name: Configure SQL Server Concurrent Session Limit
      win_shell: |
        $triggerCode = @"
          CREATE TRIGGER SQL_STIG_Connection_Limit 
          ON ALL SERVER WITH EXECUTE AS 'renamed_sa' 
          FOR LOGON 
          AS 
          BEGIN 
            IF (SELECT COUNT(1) FROM sys.dm_exec_sessions WHERE is_user_process = 1 AND original_login_name = ORIGINAL_LOGIN()) > 
              (CASE ORIGINAL_LOGIN()
                WHEN 'renamed_sa' THEN 40
                WHEN 'domain/ima.dba' THEN 150
                WHEN 'application1_login' THEN 6
                WHEN 'application2_login' THEN 20
                ELSE 1
              END)
            BEGIN 
                PRINT 'The login [' + ORIGINAL_LOGIN() + '] has exceeded its concurrent session limit.' 
                ROLLBACK; 
            END
          END;
        "@
        Invoke-Sqlcmd -Query $triggerCode -ServerInstance 'localhost' -Database 'master'
      become: yes
      become_user: WinLabAAP
      environment:
        PYTHONIOENCODING: UTF-8

    - name: Check CEIP Participation
      win_regedit:
        path: "HKEY_LOCAL_MACHINE\\Software\\Microsoft\\Microsoft SQL Server\\{{ sql_instance_id }}\\CPE"
        name: "CustomerFeedback"
      register: customer_feedback

    - name: Check Enable Error Reporting
      win_regedit:
        path: "HKEY_LOCAL_MACHINE\\Software\\Microsoft\\Microsoft SQL Server\\{{ sql_instance_id }}\\CPE"
        name: "EnableErrorReporting"
      register: enable_error_reporting

    - name: Check CEIP Participation (Version 130)
      win_regedit:
        path: "HKEY_LOCAL_MACHINE\\Software\\Microsoft\\Microsoft SQL Server\\130"
        name: "CustomerFeedback"
      register: customer_feedback_130

    - name: Check Enable Error Reporting (Version 130)
      win_regedit:
        path: "HKEY_LOCAL_MACHINE\\Software\\Microsoft\\Microsoft SQL Server\\130"
        name: "EnableErrorReporting"
      register: enable_error_reporting_130

    - name: Ensure CEIP is Disabled
      win_regedit:
        path: "HKEY_LOCAL_MACHINE\\Software\\Microsoft\\Microsoft SQL Server\\{{ sql_instance_id }}\\CPE"
        name: "CustomerFeedback"
        data: "0"
      when: customer_feedback.rc == 0 and customer_feedback.changed

    - name: Ensure Error Reporting is Disabled
      win_regedit:
        path: "HKEY_LOCAL_MACHINE\\Software\\Microsoft\\Microsoft SQL Server\\{{ sql_instance_id }}\\CPE"
        name: "EnableErrorReporting"
        data: "0"
      when: enable_error_reporting.rc == 0 and enable_error_reporting.changed

    - name: Ensure CEIP is Disabled (Version 130)
      win_regedit:
        path: "HKEY_LOCAL_MACHINE\\Software\\Microsoft\\Microsoft SQL Server\\130"
        name: "CustomerFeedback"
        data: "0"
      when: customer_feedback_130.rc == 0 and customer_feedback_130.changed

    - name: Ensure Error Reporting is Disabled (Version 130)
      win_regedit:
        path: "HKEY_LOCAL_MACHINE\\Software\\Microsoft\\Microsoft SQL Server\\130"
        name: "EnableErrorReporting"
        data: "0"
      when: enable_error_reporting_130.rc == 0 and enable_error_reporting_130.changed
