---
- name: Combined SQL Server Configuration
  hosts: all
  gather_facts: true
  become: yes
  become_method: runas
  become_user: WinLabAAP #is admin

  vars:
    permission: "VIEW ANY DATABASE"  # Real Permissions
    sql_instance_id: "MSSQL13.SQLEXPRESS" # Specify the SQL Server instance name here

  tasks:

    - name: Install NuGet provider
      win_shell: |
        Install-PackageProvider -Name NuGet -Force -Scope CurrentUser
      become: yes
      become_user: WinLabAAP

    - name: Install pymssql Python module
      win_shell: |
        Install-Module -Name pymssql -Force
      become: yes
      become_user: WinLabAAP
      environment:
        PYTHONIOENCODING: UTF-8

    - name: Check CEIP Participation
      win_regedit:
        path: "HKLM:\\Software\\Microsoft\\Microsoft SQL Server\\{{ sql_instance_id }}\\CPE"
        name: "CustomerFeedback"
      register: customer_feedback
      ignore_errors: true

    - name: Check Enable Error Reporting
      win_regedit:
        path: "HKLM:\\Software\\Microsoft\\Microsoft SQL Server\\{{ sql_instance_id }}\\CPE"
        name: "EnableErrorReporting"
      register: enable_error_reporting
      ignore_errors: true

    - name: Check CEIP Participation (Version 130)
      win_regedit:
        path: "HKLM:\\Software\\Microsoft\\Microsoft SQL Server\\130"
        name: "CustomerFeedback"
      register: customer_feedback_130
      ignore_errors: true

    - name: Check Enable Error Reporting (Version 130)
      win_regedit:
        path: "HKLM:\\Software\\Microsoft\\Microsoft SQL Server\\130"
        name: "EnableErrorReporting"
      register: enable_error_reporting_130
      ignore_errors: true

    - name: Ensure CEIP is Disabled
      win_regedit:
        path: "HKLM:\\Software\\Microsoft\\Microsoft SQL Server\\{{ sql_instance_id }}\\CPE"
        name: "CustomerFeedback"
        data: "0"
        type: dword
      when: customer_feedback.stdout == "1"
      ignore_errors: true

    - name: Ensure Error Reporting is Disabled
      win_regedit:
        path: "HKLM:\\Software\\Microsoft\\Microsoft SQL Server\\{{ sql_instance_id }}\\CPE"
        name: "EnableErrorReporting"
        data: "0"
        type: dword
      when: enable_error_reporting.stdout == "1"
      ignore_errors: true

    - name: Ensure CEIP is Disabled (Version 130)
      win_regedit:
        path: "HKLM:\\Software\\Microsoft\\Microsoft SQL Server\\130"
        name: "CustomerFeedback"
        data: "0"
        type: dword
      when: customer_feedback_130.stdout == "1"
      ignore_errors: true

    - name: Ensure Error Reporting is Disabled (Version 130)
      win_regedit:
        path: "HKLM:\\Software\\Microsoft\\Microsoft SQL Server\\130"
        name: "EnableErrorReporting"
        data: "0"
        type: dword
      when: enable_error_reporting_130.stdout == "1"
      ignore_errors: true
