---
- name: Ansible & DSC Playbook for SQL STIG
  hosts: all
  gather_facts: true
  become: yes
  become_method: runas
  become_user: WinLabAAP #is admin

  tasks:
    - name: Install NuGet provider
      win_shell: |
        Install-PackageProvider -Name NuGet -Force -Scope CurrentUser
      become: yes
      become_user: WinLabAAP
      ignore_errors: true

    - name: Install PowerShellGet
      win_shell: |
        if (-not(Get-Module -ListAvailable -Name PowerShellGet)) {
            Install-Module -Name PowerShellGet -Force -AllowClobber
        }
      args:
        executable: powershell.exe
      become: yes
      become_user: WinLabAAP
      ignore_errors: true

    - name: Install PowerStig
      win_shell: |
        if (-not(Get-Module -ListAvailable -Name PowerSTIG)) {
            Install-Module -Name PowerSTIG -Force
        }
      args:
        executable: powershell.exe
      become: yes
      become_user: WinLabAAP
      ignore_errors: true

    - name: PowerSTIG prereqs not necessarily covered in previous task
      win_psmodule:
        name: "{{ item.name }}"
        required_version: "{{ item.version }}"
        state: present
        allow_clobber: yes
      loop:
        - name: AuditPolicyDsc
          version: 1.4.0.0
        - name: SecurityPolicyDsc
          version: 2.10.0.0
        - name: PSDscResources
          version: 2.12.0.0
      become: yes
      become_user: WinLabAAP
      ignore_errors: true

    - name: Create Audit directory
      win_file:
        path: C:\\audits
        state: directory
      become: yes
      become_user: WinLabAAP
      ignore_errors: true

    - name: Generate PowerSTIG DSC MOF
      win_shell: |
        {{ lookup('template', 'templates/sql_stig_dsc.ps.j2') }} 
      become: yes
      become_user: WinLabAAP
      ignore_errors: true

    - name: Apply generated PowerSTIG MOF
      win_shell: |
        Start-DscConfiguration -Path C:\Windows\SQL2016 -Force -Wait -Verbose
      become: yes
      become_user: WinLabAAP
      ignore_errors: true

    - name: Send webhook message
      uri:
        url: "https://validatek.webhook.office.com/webhookb2/5688d95a-edaa-4fa8-a7de-6496242c0fdc@c8ebb8f5-6ec3-41bd-99b6-e4aafe702967/IncomingWebhook/ca5b49ae03c0492e8c1a1949ac9c5bb9/d19e7d29-9069-4f3d-9178-90a58c17322e"
        method: POST
        body: "{{ ansible_facts }}"
        body_format: json
        status_code: 200
      ignore_errors: true
