---
- name: Configure SQL Server Customer Feedback and Error Reporting
  hosts: all
  gather_facts: true
  become: yes
  vars:
    sql_instance_id: "MSSQLSERVER" # Specify the SQL Server instance name here
  tasks:
    - name: Check CEIP Participation
      win_regedit:
        path: "HKEY_LOCAL_MACHINE\\Software\\Microsoft\\Microsoft SQL Server\\{{ sql_instance_id }}\\CPE"
        name: "CustomerFeedback"
      register: customer_feedback

    - name: Check Enable Error Reporting
      win_regedit:
        path: "HKEY_LOCAL_MACHINE\\Software\\Microsoft\\Microsoft SQL Server\\{{ sql_instance_id }}\\CPE"
        name: "EnableErrorReporting"
      register: enable_error_reporting

    - name: Check CEIP Participation (Version 130)
      win_regedit:
        path: "HKEY_LOCAL_MACHINE\\Software\\Microsoft\\Microsoft SQL Server\\130"
        name: "CustomerFeedback"
      register: customer_feedback_130

    - name: Check Enable Error Reporting (Version 130)
      win_regedit:
        path: "HKEY_LOCAL_MACHINE\\Software\\Microsoft\\Microsoft SQL Server\\130"
        name: "EnableErrorReporting"
      register: enable_error_reporting_130

    - name: Ensure CEIP is Disabled
      win_regedit:
        path: "HKEY_LOCAL_MACHINE\\Software\\Microsoft\\Microsoft SQL Server\\{{ sql_instance_id }}\\CPE"
        name: "CustomerFeedback"
        data: "0"
      when: customer_feedback.rc == 0 and customer_feedback.changed

    - name: Ensure Error Reporting is Disabled
      win_regedit:
        path: "HKEY_LOCAL_MACHINE\\Software\\Microsoft\\Microsoft SQL Server\\{{ sql_instance_id }}\\CPE"
        name: "EnableErrorReporting"
        data: "0"
      when: enable_error_reporting.rc == 0 and enable_error_reporting.changed

    - name: Ensure CEIP is Disabled (Version 130)
      win_regedit:
        path: "HKEY_LOCAL_MACHINE\\Software\\Microsoft\\Microsoft SQL Server\\130"
        name: "CustomerFeedback"
        data: "0"
      when: customer_feedback_130.rc == 0 and customer_feedback_130.changed

    - name: Ensure Error Reporting is Disabled (Version 130)
      win_regedit:
        path: "HKEY_LOCAL_MACHINE\\Software\\Microsoft\\Microsoft SQL Server\\130"
        name: "EnableErrorReporting"
        data: "0"
      when: enable_error_reporting_130.rc == 0 and enable_error_reporting_130.changed
