---
- name: SQL Server Security Compliance
  hosts: all
  gather_facts: true
  become: yes
  vars:
    permission: "VIEW ANY DATABASE"  # Real Permissions
  tasks:
    - name: Check if SQL Server is Clustered or has Availability Groups
      win_shell: |
        $IsClustered = (Get-ItemProperty -Path 'HKLM:\SOFTWARE\Microsoft\Microsoft SQL Server\MSSQLServer\Cluster').IsClustered
        $IsHadrEnabled = (Get-ItemProperty -Path 'HKLM:\SOFTWARE\Microsoft\Microsoft SQL Server\MSSQLServer').IsHadrEnabled
        $Permissions = Invoke-Sqlcmd -Query "SELECT * FROM fn_my_permissions(NULL, 'server')" -ServerInstance localhost

        $IsClustered, $IsHadrEnabled, $Permissions
      register: sql_server_status

    - name: Fail the playbook if conditions are not met
      fail:
        msg: "Security compliance check failed. Review the playbook output for details."
      when: "sql_server_status.stdout[0] == 1 and sql_server_status.stdout[1] == 0 and (sql_server_status.stdout[2] | length > 0)"

    - name: Remove unauthorized permissions for Local System account
      win_shell: |
        USE Master;
        REVOKE {{ permission }} TO [NT AUTHORITY\SYSTEM]
      when: "sql_server_status.stdout[2] | length > 0"
